---
title: "SQuID"
output:
  learnr::tutorial:
    progressive: true
    allow_skip: true
    theme: cosmo
    css: css/stylesheet.css
runtime: shiny_prerendered
description: >
  SQuID integrated learning environment
---
<!--bootstrap, cerulean, cosmo, darkly, flatly, journal, lumen, paper, readable, sandstone, simplex, spacelab, united, yeti rmarkdown themes-->
```{r setup, include=FALSE}
#devtools::install_github("rundel/learnrhash")
library(shiny)
library(learnr)
library(lme4)
library(squidSim)
knitr::opts_chunk$set(echo = FALSE)
source("./variables/var_general.R")
source("./variables/var_fullmodel.R")
source("./variables/var_modules.R")
source("./text/text.R")  
#any text with equation in it should be wrapped in a <p></p> in order for cat(.) to properly print it. 
#but not titles because then things get messed up.
for(i in 1:length(text)){
  list.idx <- !grepl("*[t]itle*|*image*",names(text[[i]]),ignore.case = T)
  if(any(list.idx)){
    text[[i]][list.idx] <- rapply(text[[i]][list.idx],function(x)paste0("<p>",x,"</p>"),how="replace")
  }
}
#place each list element into the global environment
list2env(text, names(text),envir=.GlobalEnv)
source("./submission.R")
 
# display R code in console format
displayRCode <- function(RCode){
  return(wellPanel(class="highlight-source-r ", HTML(paste0("<h3>R code:</h3>", RCode))))
}

#code to allow a certain amount of retries: question_module_server_impl <- function(
question_module_server_impl <-function (input, output, session, question, question_state = NULL) 
{
  ns <- getDefaultReactiveDomain()$ns
  # new ============================
  # set counter
  val <- reactiveValues(
    numtry = 0
  )
  # ================================
  
  question$seed <- learnr:::random_seed()
  submitted_answer <- reactiveVal(NULL, label = "submitted_answer")
  is_correct_info <- reactive(label = "is_correct_info", {
    if (is.null(submitted_answer())) 
      return(NULL)
    ret <- question_is_correct(question, submitted_answer())
    # new : Increment counter =======
    isolate(val$numtry <- val$numtry+1)
    # ===============================
    if (!inherits(ret, "learnr_mark_as")) {
      stop("`question_is_correct(question, input$answer)` must return a result from `correct`, `incorrect`, or `mark_as`")
    }
    ret
  })
  is_done <- reactive(label = "is_done", {
    if (is.null(is_correct_info())) 
      return(NULL)
    # updated ====================================================
    (!isTRUE(question$allow_retry>0)) || is_correct_info()$correct
    # ============================================================
  })
  button_type <- reactive(label = "button type", {
    if (is.null(submitted_answer())) {
      "submit"
    }
    else {
      if (is.null(is_correct_info())) {
        stop("`is_correct_info()` is `NULL` in a place it shouldn't be")
      }
      if (is_correct_info()$correct) {
        "correct"
      } else {
        # not correct
        # updated =====================================
        if (isTRUE(val$numtry<question$allow_retry)|(question$allow_retry&is.logical(question$allow_retry))) {
          # not correct, but may try again
          "try_again"
        } else {
          # not correct and can not try again
          "incorrect"
        }
      }
    }
  })
  answer_is_valid <- reactive(label = "answer_is_valid", {
    if (is.null(submitted_answer())) {
      learnr:::question_is_valid(question, input$answer)
    }
    else {
      learnr:::question_is_valid(question, submitted_answer())
    }
  })
  init_question <- function(restoreValue = NULL) {
    if (question$random_answer_order) {
      is_visible_option <- !learnr:::answer_type_is_function(question$answers)
      question$answers[is_visible_option] <<- learnr:::shuffle(question$answers[is_visible_option])
    }
    submitted_answer(restoreValue)
  }
  past_submission_answer <- learnr:::retrieve_question_submission_answer(session, 
                                                                question$label)
  init_question(past_submission_answer)
  output$action_button_container <- renderUI({
    learnr:::question_button_label(question, button_type(), answer_is_valid())
  })
  output$message_container <- renderUI({
    req(!is.null(is_correct_info()), !is.null(is_done()))
    learnr:::withLearnrMathJax(learnr:::question_messages(question, messages = is_correct_info()$messages, 
                                        is_correct = is_correct_info()$correct, is_done = is_done()))
  })
  output$answer_container <- renderUI({
    if (is.null(submitted_answer())) {
      return(learnr:::withLearnrMathJax(question_ui_initialize(question, 
                                                      isolate(input$answer))))
    }
    if (is.null(is_done())) {
      return(NULL)
    }
    if (is_done()) {
      return(learnr:::withLearnrMathJax(question_ui_completed(question, 
                                                     submitted_answer())))
    }
    return(learnr:::withLearnrMathJax(question_ui_try_again(question, 
                                                   submitted_answer())))
  })
  observeEvent(input$action_button, {
    if (button_type() == "try_again") {
      submitted_answer(NULL)
      learnr:::event_trigger(session, "reset_question_submission", 
                    data = list(label = as.character(question$label), 
                                question = as.character(question$question)))
      return()
    }
    submitted_answer(input$answer)
    learnr:::event_trigger(session = session, event = "question_submission", 
                  data = list(label = as.character(question$label), 
                              question = as.character(question$question), answer = as.character(input$answer), 
                              correct = is_correct_info()$correct))
  })
  observe({
    req(submitted_answer(), is.reactive(question_state))
    current_answer_state <- list(type = "question", answer = submitted_answer(), 
                                 correct = is_correct_info()$correct)
    question_state(current_answer_state)
  })
}
assignInNamespace("question_module_server_impl",question_module_server_impl,ns="learnr")

```

<!--
```{r quiz2}
question("Which is good",answer("good",correct=TRUE),
         answer("bad",correct=F),
         allow_retry=2)
```
-->

<!-- <object data='https://bertvdveen.shinyapps.io/app1/' frameborder="0" style="width: 100%; height: 850px;overflow:hidden;display:block"></object> 

```{r quizn, echo = FALSE}
question("What did you explore in the above app?",
  answer("Measurement error", correct = TRUE),
  answer("Number of individuals", correct = FALSE),
  type = "learnr_radio",
  allow_retry = TRUE,
  random_answer_order = TRUE
)
```
-->

```{r portal, echo=F, child = "./modules/portal.Rmd" }
```

<!--Basic lessons about variance-->

```{r module_1, echo=F, child = "./modules/module_1.Rmd" }
```

<!--Non-stochastic environments-->
```{r module_2, echo=F, child = "./modules/module_2.Rmd" }
```

<!--Random-slope regression-->
```{r module_3, echo=F, child = "./modules/module_3.Rmd" }
```

<!--Multidimensional Phenotypic Plasticity (MDPP)-->
```{r module_4, echo=F, child = "./modules/module_4.Rmd" }
```

<!--MDPP and random regression-->
```{r module_5, echo=F, child = "./modules/module_5.Rmd" }
```

<!--Multiple traits-->
```{r module_6, echo=F, child = "./modules/module_6.Rmd" }
```

## (optional) Save progress report

```{r context="setup"}
submission_ui
```

```{r context="server"}
submission_server()
```

<!--Non-Gaussian traits-->
```{r extra_1, echo=F, child = "./modules/extra_1.Rmd" }
```