
## Extra 1: Non-Gaussian traits

```{r extra1_step1_title, results="asis"}
  cat("###", extra$Extra1Step1_txt$title)
```

```{r extra1_step1, results="asis"}
  #### goal ####
  cat(extra$Extra1Step1_txt$goal)
  
  #### Introduction ####
  cat(extra$Extra1Step1_txt$intro)

  cat(extra$Extra1Step1_txt$para1)
  
  
  cat(extra$Extra1Step1_txt$para1_image)
  cat(extra$Extra1Step1_txt$para1_image_caption)

  cat(extra$Extra1Step1_txt$para2)
  
  cat(placeholder_image) #app 5

  cat(extra$Extra1Step1_txt$para3)

  cat(placeholder_image) #app 6

  cat(extra$Extra1Step1_txt$para6)

  cat(extra$Extra1Step1_txt$para4)
  
  cat(placeholder_image) #app 7

  cat(extra$Extra1Step1_txt$para5)
  
  cat(extra$Extra1Step1_txt$exercise)
  
  cat(placeholder_image) #app 8

  
  cat(extra$Extra1Step1_txt$para7)

  h4(extra$Extra1Step1_txt$para8_title)  
  
  HTML(extra$Extra1Step1_txt$para8)
  
 h4(extra$Extra1Step1_txt$para9_title)
  
  HTML(extra$Extra1Step1_txt$para9)
  
  HTML(placeholder_image) #app 9
  
 cat(extra$Extra1Step1_txt$para10)


```

```{r extra1_step2_title, results="asis"}
cat("###", extra$Extra1Step2_txt$title)
```

```{r extra1_step2, results="asis"}
  #### goal ####
  cat(extra$Extra1Step2_txt$goal)
  
  #### Introduction ####
  cat(extra$Extra1Step2_txt$intro)
  
  cat(extra$Extra1Step2_txt$para1)
  
  cat(extra$Extra1Step2_txt$para1_eq1)
  cat(extra$Extra1Step2_txt$para1_eq2)
  cat(extra$Extra1Step2_txt$para1_eq3)
  
  cat(extra$Extra1Step2_txt$para2)
  
  cat(extra$Extra1Step2_txt$para2_eq1)
  cat(extra$Extra1Step2_txt$para2_eq2)
  cat(extra$Extra1Step2_txt$para2_eq3)
 
  cat(extra$Extra1Step2_txt$para3)
  
  cat(extra$Extra1Step2_txt$para3_eq1)
  cat(extra$Extra1Step2_txt$para3_eq2)
  cat(extra$Extra1Step2_txt$para3_eq3)
  
  cat(extra$Extra1Step2_txt$para4)
  
  cat(extra$Extra1Step2_txt$para4_eq1)
  
  cat(extra$Extra1Step2_txt$exercise)

  cat(placeholder_image) #app 10

```

```{r extra1_step3_title, results="asis"}
cat("###", extra$Extra1Step3_txt$title)
```

```{r extra1_step3, results="asis"}
#### goal ####
  cat(extra$Extra1Step3_txt$goal)

  #### Introduction 1 ####
  cat(extra$Extra1Step3_txt$para1)
  
  
  cat(extra$Extra1Step3_txt$para1_eq1)
  cat(extra$Extra1Step3_txt$para1_eq2)
  cat(extra$Extra1Step3_txt$para1_eq3)
  
  cat(extra$Extra1Step3_txt$exercise)
  
```

```{r ex2, exercise=TRUE, exercise.cap = "Code exercise.", warning=FALSE, message=FALSE}
# number of values generated
n <- 10000
# Use the Gaussian distribution to generate n values
# with a mean of 0 and a standard-deviation of 1.
y_prime <- rnorm(n, 0, 1)
# Convert these values to probabilities
# using the inverse-logit function.
p <- plogis(y_prime)
# Use the Bernoulli distribution to generate n values
# with the probability vector p.
y <- rbinom(n, size = 1, prob = p)
# Note that we used the binomial function with one trial,
# which is equivalent to the Bernoulli distribution.
```

```{r extra1_step3_con, results="asis"}
  cat(extra$Extra1Step3_txt$para2)

  #### Introduction 2 ####
  cat(extra$Extra1Step3_txt$intro2)
  
  cat(extra$Extra1Step3_txt$intro2_eq1)
  cat(extra$Extra1Step3_txt$intro2_eq2)
  cat(extra$Extra1Step3_txt$intro2_eq3)
  cat(extra$Extra1Step3_txt$intro2_eq4)

  cat(extra$Extra1Step3_txt$para3)
  
  cat(extra$Extra1Step3_txt$para4)
  
  cat(extra$Extra1Step3_txt$para4_eq1)
  cat(extra$Extra1Step3_txt$para4_eq2)
  cat(extra$Extra1Step3_txt$para4_eq3)
  cat(extra$Extra1Step3_txt$para4_eq4)

  cat(extra$Extra1Step3_txt$exercise2)
  
  cat(placeholder_image) #app11

```

```{r ex3-setup, exercise=FALSE, warning=FALSE, message=FALSE, echo=TRUE, exercise.cap = "Set-up for exercise code chunk."}
library(lme4)
library(squidSim)
get_data <- function(n,r,Vi,Vr){
  if(n>1000)stop("Please don't make our server hamsters work that hard..")
  squid_data <- simulate_population(
  data_structure = make_structure(structure = paste0("Individual(",n,")"), repeat_obs=r),
  parameters = list(
    Individual = list(
      vcov = Vi
    ),
    residual = list(
      vcov = Vr
    )
  ),
  family = "poisson", 
  link = "log",
  response_names = "Phenotype"
)
  data <- get_population_data(squid_data)
  return(data)
}
```

```{r ex3, exercise=TRUE, exercise.cap = "Code exercise.", warning=FALSE, message=FALSE}
# n is the number of individuals
# r is the number of repetitions for each individual
# Vi is the variance for individuals
# Vr is residual variance 
data <- get_data(n = 50, r = 2, Vi = 0.5, Vr = 0.5)
GLMM <- glmer(Phenotype ~ 0 + (1|Individual), family = poisson(link=log), data = data)
summary(GLMM)
```

```{r extra1_step3_con2, results="asis"}
  cat(extra$Extra1Step3_txt$conclusion)
```
